
server:
  port: 7090

spring.datasource.url: jdbc:mysql://localhost:3306/ApolloConfigDB-uat?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
      show-sql: true #打印执行的sql语句
